# Generated by Django 6.0.6 on 2026-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RemoveField(
            model_name='about',
            name='features',
        ),
        migrations.RemoveField(
            model_name='about',
            name='welcome_title',
        ),
        migrations.AddField(
            model_name='about',
            name='feature1',
            field=models.CharField(default='Experienced Veterinarians', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='feature2',
            field=models.CharField(default='Modern Equipment', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='feature3',
            field=models.CharField(default='Emergency Services', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='feature4',
            field=models.CharField(default='Affordable Pricing', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='welcome_text',
            field=models.CharField(default='WELCOME TO ODY MOBILE VETERINARY CLINIC', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
