# Generated by Django 6.0.6 on 2026-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='media',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Pets', 'Pets'), ('Surgery', 'Surgery'), ('Videos', 'Videos')], default='Pets', max_length=30),
        ),
    ]
