# Generated by Django 6.0.6 on 2026-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('working_days', models.CharField(default='Monday - Saturday', max_length=100)),
                ('working_hours', models.CharField(default='8:30 AM - 5:30 PM', max_length=100)),
                ('emergency_text', models.CharField(default='24-Hour Emergency Services', max_length=200)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
