# Generated by Django 6.0.6 on 2026-07-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
        migrations.AlterField(
            model_name='contact',
            name='emergency_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
