# Generated by Django 6.0.6 on 2026-07-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
    ]
