# Generated by Django 6.0.6 on 2026-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_hero_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={},
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='background_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='created_at',
        ),
        migrations.AddField(
            model_name='hero',
            name='tag',
            field=models.CharField(default='Trusted Veterinary Clinic', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_button_link',
            field=models.CharField(default='/contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_button_text',
            field=models.CharField(default='Book Appointment', max_length=50),
        ),
        migrations.AlterField(
            model_name='hero',
            name='secondary_button_link',
            field=models.CharField(default='/services', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='secondary_button_text',
            field=models.CharField(default='Our Services', max_length=50),
        ),
    ]
